### ISSUE TITLE
Reorganize repository structure

### ISSUE THREAD

**Issue by luandy64** [DeputyApp/singer-tap-deputy#4]
Following the [Singer Tap Template](https://github.com/singer-io/singer-tap-template), 
the directory should look something like:

```
/stitch-stream-deputy
  - README.md
  - LICENSE
  - .gitignore
  - MANIFEST.in
  - setup.py
  - stitch_stream_deputy/
    - schemas/
      - ...
    - __init__.py
```

**Comment by dmosorast** [comment]
Since schemas are dynamic, there doesn't need to be a `schemas` directory. The organization looks good, just missing some non-essential packaging/licensing items.
